[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
    "python manage.py migrate"
]

[start]
cmd = "gunicorn galeria.wsgi --bind 0.0.0.0:$PORT" 