# Generated by Django 5.1.7 on 2025-06-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImagemGaleria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome da Imagem"),
                ),
                ("album", models.CharField(max_length=100, verbose_name="Álbum")),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "imagem",
                    models.ImageField(upload_to="galeria/", verbose_name="Imagem"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "data_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Upload"
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem da Galeria",
                "verbose_name_plural": "Imagens da Galeria",
                "ordering": ["-data", "nome"],
            },
        ),
    ]
