# Generated by Django 5.1.7 on 2025-06-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artistas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MidiaGaleria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("arquivo", models.FileField(upload_to="galeria/midias/")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("imagem", "Imagem"), ("video", "Vídeo")],
                        max_length=10,
                    ),
                ),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ImagemGaleria",
        ),
    ]
