# Generated by Django 5.1.7 on 2025-06-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artistas", "0002_midiagaleria_delete_imagemgaleria"),
    ]

    operations = [
        migrations.AddField(
            model_name="midiagaleria",
            name="peso",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="midiagaleria",
            name="tipo",
            field=models.CharField(max_length=10),
        ),
    ]
