# Generated by Django 5.1.7 on 2025-06-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artistas", "0003_midiagaleria_peso_alter_midiagaleria_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Álbum"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "ano_lancamento",
                    models.PositiveIntegerField(verbose_name="Ano de Lançamento"),
                ),
                (
                    "capa",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="capas_albuns/",
                        verbose_name="Capa do Álbum",
                    ),
                ),
                (
                    "artista_principal",
                    models.CharField(max_length=100, verbose_name="Artista Principal"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MidiaGaleria",
        ),
    ]
